async function get<T>(path: string): Promise<T> {
  const response = await fetch(`/api${path}`);
  if (!response.ok) {
    throw new Error(`GET ${path} failed: ${response.status}`);
  }
  return response.json() as Promise<T>;
}

import type {
  Anecdote,
  BacktestBundle,
  Benchmarks,
  ComebackPrediction,
  EncorePrediction,
  RunningOrder,
  CalendarHeatmap,
  CooccurrenceHeatmap,
  SetlistFeatureSummary,
  SongFeature,
  SongPositionHeatmap,
  SongsByYearHeatmap,
  City,
  CoverArtist,
  Encores,
  SetlistDuration,
  SongMapPoint,
  TourSummary,
  ClusterDetail,
  ClusterSummary,
  CountryPrediction,
  NextDate,
  Overview,
  SetlistLength,
  SetlistTrend,
  Song,
  SongPrediction,
  SongRole,
  Transitions,
  Venue,
} from "./types";

export const api = {
  overview: () => get<Overview>("/stats/overview"),
  songs: () => get<Song[]>("/songs"),
  nextSetlist: () => get<SongPrediction[]>("/predictions/next-setlist"),
  setlistLength: () => get<SetlistLength>("/predictions/setlist-length"),
  songRole: (songId: number) => get<SongRole>(`/predictions/song-role/${songId}`),
  nextDate: () => get<NextDate>("/predictions/next-date"),
  nextCountry: () => get<CountryPrediction[]>("/predictions/next-country"),
  venues: () => get<Venue[]>("/analysis/venues"),
  setlistTrend: () => get<SetlistTrend>("/analysis/setlist-trend"),
  clusters: () => get<ClusterSummary[]>("/analysis/clusters"),
  clusterDetail: (clusterId: number) => get<ClusterDetail>(`/analysis/clusters/${clusterId}`),
  transitions: (songId: number) => get<Transitions>(`/analysis/transitions/${songId}`),
  anecdotes: () => get<Anecdote[]>("/analysis/anecdotes"),
  tours: () => get<TourSummary[]>("/analysis/tours"),
  covers: () => get<CoverArtist[]>("/analysis/covers"),
  encores: () => get<Encores>("/analysis/encores"),
  songMap: () => get<SongMapPoint[]>("/analysis/song-map"),
  cities: () => get<City[]>("/analysis/cities"),
  setlistDuration: () => get<SetlistDuration>("/predictions/setlist-duration"),
  songFeatures: () => get<SongFeature[]>("/analysis/song-features"),
  setlistFeatureSummary: () => get<SetlistFeatureSummary>("/analysis/setlist-features/summary"),
  heatmapSongsByYear: () => get<SongsByYearHeatmap>("/analysis/heatmap/songs-by-year"),
  heatmapCalendar: () => get<CalendarHeatmap>("/analysis/heatmap/calendar"),
  heatmapSongPositions: () => get<SongPositionHeatmap>("/analysis/heatmap/song-positions"),
  heatmapCooccurrence: () => get<CooccurrenceHeatmap>("/analysis/heatmap/cooccurrence"),
  benchmarks: () => get<Benchmarks>("/predictions/benchmarks"),
  backtests: () => get<BacktestBundle>("/predictions/backtests"),
  runningOrder: () => get<RunningOrder>("/predictions/running-order"),
  encorePrediction: () => get<EncorePrediction>("/predictions/encore"),
  comebackPrediction: () => get<ComebackPrediction>("/predictions/comeback"),
};
